name: CI synthesizer

on:
  push:
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [raspberrypi5, raspberrypi4-64]
    steps:
      - name: Free disk space
        uses: endersonmenezes/free-disk-space@v3
        with:
          remove_android: true
          remove_tool_cache: true

      - name: Install host dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git python3 unzip rsync bc libncurses5-dev \
            bison flex cpio wget libssl-dev libgnutls28-dev

      - name: Checkout this repo
        uses: actions/checkout@v6

      - name: Checkout Buildroot 2025.02.10
        uses: actions/checkout@v6
        with:
          repository: "buildroot/buildroot"
          ref: "2025.02.10"
          path: buildroot

      - name: Build for ${{ matrix.board }}
        run: |
          make -C buildroot BR2_EXTERNAL=../ O=../output ${{ matrix.board }}_defconfig
          make -C buildroot O=../output

      - name: Rename Image
        run: |
          mv output/images/sdcard.img output/images/synthesizer-os-${{ github.ref_name }}-${{ matrix.board }}.img

      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          files: |
            output/images/synthesizer-os-${{ github.ref_name }}-${{ matrix.board }}.img